/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import { ArrowRight, BadgeCheck, MapPin, Star } from "lucide-react";
import type { Doctor } from "@/types/doctor";

export default function DoctorCard({ doctor }: { doctor: Doctor }) {
  const hasAvailability = !doctor.availability.startsWith("No");
  return <article className="group grid gap-5 border-b border-[var(--line)] bg-[var(--card)] p-5 transition duration-300 hover:bg-[var(--background)] sm:grid-cols-[130px_minmax(0,1fr)_150px] sm:items-center">
    <div className="relative overflow-hidden bg-[var(--sand)]"><img src={doctor.image} alt={doctor.name} className="aspect-[4/3] w-full object-cover object-top saturate-[0.8] transition duration-500 group-hover:scale-[1.025] sm:aspect-[4/5]" /><BadgeCheck className="absolute bottom-2 right-2 size-5 fill-white text-[var(--brand)]" /></div>
    <div className="min-w-0"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-lg font-medium tracking-[-0.02em]">{doctor.name}</h3><p className="mt-1 text-sm text-[var(--brand)]">{doctor.specialty}</p></div>{doctor.reviews > 0 && <span className="flex items-center gap-1 text-sm"><Star className="size-4 fill-[var(--accent)] text-[var(--accent)]" />{doctor.rating} <small className="text-[var(--muted)]">({doctor.reviews})</small></span>}</div><p className="mt-3 flex items-center gap-1.5 text-xs text-[var(--muted)]"><MapPin size={14} className="text-[var(--brand)]" />{doctor.location}</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 border-t border-[var(--line)] pt-4 text-xs"><span><small className="block text-[var(--muted)]">Experience</small><strong className="mt-1 block font-medium">{doctor.experience} years</strong></span><span><small className="block text-[var(--muted)]">Consultation</small><strong className="mt-1 block font-medium">₹{doctor.fee}</strong></span><span><small className="block text-[var(--muted)]">Availability</small><strong className={`mt-1 flex items-center gap-1.5 font-medium ${hasAvailability ? "text-[var(--accent)]" : "text-[var(--muted)]"}`}><i className={`size-1.5 rounded-full ${hasAvailability ? "bg-[var(--accent)]" : "bg-[var(--muted)]"}`} />{doctor.availability}</strong></span></div></div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-1"><Link href={`/booking/${doctor.id}`} className="group/book bg-[var(--brand)] px-4 py-3 text-center text-xs font-semibold text-white hover:bg-[var(--brand-deep)]">Book <ArrowRight size={14} className="ml-1 inline transition group-hover/book:translate-x-1" /></Link><Link href={`/doctors/${doctor.id}`} className="border border-[var(--line)] px-4 py-3 text-center text-xs font-semibold hover:border-[var(--foreground)]">View profile</Link></div>
  </article>;
}
